### Site Settings ###
title               : Morgan Schwartz, PhD
description         : >-
                      I am a biologist passionate about developing open source software that
                      puts deep learning models in the hands of biologists at the bench.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : msschwartz21/msschwartz21.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)
cv_filename: MorganSchwartz_CV.pdf


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Morgan Schwartz
  image             : profile.jpeg
  # behance           : your_username
# dribbble          : your_username
  email             : msschwartz@caltech.edu
  # facebook          : your_username
  github            : msschwartz21
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : morgan-schwartz-5b2929a9
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  # twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
  orcid            : 0000-0001-8131-9125
  googlescholar    : dLl7P3kAAAAJ&hl


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  publications:
    output: true
    permalink: /publications/:name
  software:
    output: true
    permalink: /software/:name


### Disqus ###
# disqus:
#   shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "software"
    values:
      layout: page


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
